
# handle the QUIETLY and REQUIRED arguments and set MPEG2_FOUND to TRUE if 
# all listed variables are TRUE

SET( MEDV4D_TARGETS Common Imaging DICOMInterface GUI )

INCLUDE(FindPackageHandleStandardArgs.cmake)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MedV4D MEDV4D_INCLUDE_DIR MEDV4D_COMMON_LIBRARY MEDV4D_IMAGING_LIBRARY MEDV4D_DICOM_INTERFACE_LIBRARY  MPEG2_INCLUDE_DIR)
