CMAKE_MINIMUM_REQUIRED(VERSION 2.8)
# handle the QUIETLY and REQUIRED arguments and set MPEG2_FOUND to TRUE if 
# all listed variables are TRUE


INCLUDE( "${MEDV4D_CMAKE_MODULES_DIR}/MedV4DAdditionalLibs.cmake" NO_POLICY_SCOPE )


SET( MEDV4D_FIND_COMPONENTS Common Imaging DICOMInterface GUI )

SET( MEDV4D_INCLUDE_DIR "${MEDV4D_ROOT_DIRECTORY}/include" )
SET( MEDV4D_INCLUDE_DIRS_3RD_PARTY ${MEDV4D_INCLUDE_DIRS_3RD_PARTY} ${MEDV4D_INCLUDE_DIR}/3rdParty )
SET( MEDV4D_LIBRARY_VARIABLES )
FOREACH( component ${MEDV4D_FIND_COMPONENTS} )
	STRING( TOUPPER ${component} _COMPONENT )
	SET( MEDV4D_${_COMPONENT}_LIBRARY ${component} )
	SET( MEDV4D_LIBRARY_VARIABLES ${MEDV4D_LIBRARY_VARIABLES} MEDV4D_${_COMPONENT}_LIBRARY  )
	SET( MEDV4D_LIBRARIES ${MEDV4D_LIBRARIES} ${MEDV4D_${_COMPONENT}_LIBRARY} )
ENDFOREACH( component )

INCLUDE("FindPackageHandleStandardArgs")
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MedV4D REQUIRED_VARS MEDV4D_INCLUDE_DIR ${MEDV4D_LIBRARY_VARIABLES} MEDV4D_LIBRARIES_3RD_PARTY MEDV4D_INCLUDE_DIRS_3RD_PARTY )

