
IF(NOT MEDV4D_OUTPUT_PREFIX_AND_POSTFIX_ALREADY_SET )

	IF(WIN32)
		IF( CMAKE_CL_64 )
			SET( ARCH_POSTFIX "w64" )
		ELSE( CMAKE_CL_64 )
			SET( ARCH_POSTFIX "w32" )
		ENDIF( CMAKE_CL_64 )
	ELSE(WIN32)
		SET( ARCH_POSTFIX ${CMAKE_SYSTEM_PROCESSOR} )
	ENDIF(WIN32)

	SET( MEDV4D_DEBUG_POSTFIX "_${ARCH_POSTFIX}d" )
	SET( MEDV4D_RELEASE_POSTFIX "_${ARCH_POSTFIX}" )
	SET( MEDV4D_LIBRARY_PREFIX "M4D_" )
	SET( MEDV4D_PLATFORM_LIBRARY_PREFIX "lib${MEDV4D_LIBRARY_PREFIX}" )

	SET( MEDV4D_OUTPUT_PREFIX_AND_POSTFIX_ALREADY_SET 1 )

	MARK_AS_ADVANCED( 
		MEDV4D_DEBUG_POSTFIX 
		MEDV4D_RELEASE_POSTFIX
		MEDV4D_LIBRARY_PREFIX
		MEDV4D_PLATFORM_LIBRARY_PREFIX
		)
ENDIF(NOT MEDV4D_OUTPUT_PREFIX_AND_POSTFIX_ALREADY_SET )
