

OPTION( MEDV4D_CUDA_ENABLED "Enable CUDA support" OFF )
OPTION( USE_TBB "Use Threading Building Blocks" OFF )
IF(USE_TBB)
	ADD_DEFINITIONS(-DUSE_TBB)
ENDIF(USE_TBB)

IF(WIN32)
	SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -D_CRT_SECURE_NO_WARNINGS -DBOOST_FILESYSTEM_VERSION=2" )
	SET(CMAKE_CXX_FLAGS_DEBUG "/MTd /ZI /Od -DDEBUG_LEVEL=10 -DDEBUG_ADITIONAL_INFO")
	SET(CMAKE_CXX_FLAGS_RELEASE "/MT")
ELSE(WIN32)
	OPTION( GPROFILING "enable GProf" OFF )
	IF(GPROFILING)
		SET( PROFILING_OPTIONS "-pg" )
	ENDIF(GPROFILING)

	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-deprecated -DDCOMPAT_H -DHAVE_CONFIG_H -DHAVE_SSTREAM -DBOOST_FILESYSTEM_VERSION=2" )
	SET(CMAKE_CXX_FLAGS_DEBUG "-ggdb ${PROFILING_OPTIONS} -DDEBUG_LEVEL=10 -DDEBUG_ADITIONAL_INFO")
	SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -msse2 ${PROFILING_OPTIONS}" )
ENDIF(WIN32)
