


# Use FIND_PACKAGE( DevIL COMPONENTS ... ) to enable modules IL, ILU, ILUT

SET( DEVIL_ALL_COMPONENTS "IL" "ILU" "ILUT" )


IF( DevIL_FIND_COMPONENTS )
	FOREACH( component ${DevIL_FIND_COMPONENTS} )
		STRING( TOUPPER ${component} _COMPONENT )
		SET( DEVIL_USE_${_COMPONENT} 1 )
	ENDFOREACH( component )
ELSE( DevIL_FIND_COMPONENTS )
	FOREACH( component ${DEVIL_ALL_COMPONENTS} )
		SET( DEVIL_USE_${component} 1 )
	ENDFOREACH( component )
ENDIF( DevIL_FIND_COMPONENTS )


SET( DEVIL_LIBRARY_DIRS )
SET( DEVIL_LIBRARIES )
SET( DEVIL_INCLUDE_DIRS )

FOREACH( component ${DEVIL_ALL_COMPONENTS} )
	IF( DEVIL_USE_${component} )
		FIND_LIBRARY( DEVIL_LIB_${component} ${component} HINTS ${DEVIL_LIBRARY_DIRS} )

		SET( DEVIL_LIBRARIES ${DEVIL_LIBRARIES} ${DEVIL_LIB_${component}} )
	ENDIF( DEVIL_USE_${component} )
ENDFOREACH( component )

INCLUDE_DIRECTORIES( ${DEVIL_INCLUDE_DIRS} )
SET( DEVIL_FOUND 1 )


IF( NOT DEVIL_FOUND )
	IF( DevIL_FIND_REQUIRED )
		MESSAGE( FATAL_ERROR "DevIL not found!!!")
	ELSE( DevIL_FIND_REQUIRED )
		MESSAGE( STATUS "Warning - lib DevIL not found!" )
	ENDIF( DevIL_FIND_REQUIRED )
ENDIF( NOT DEVIL_FOUND )
