INCLUDE(FindPackageHandleStandardArgs)

SET( OIS_ROOT_DIR "OIS_ROOT_DIR-NOTFOUND" CACHE PATH "Path to OIS" )

FIND_PATH(OIS_INCLUDE_DIR OIS.h 
	HINTS ${OIS_ROOT_DIR} ${OIS_ROOT_DIR}/includes
	PATH_SUFFIXES includes
	DOC "The path the the directory that contains OIS.h"
)

FIND_LIBRARY(OIS_LIBRARIES_RELEASE
	PATHS ${OIS_ROOT_DIR}
	NAMES OIS
	PATH_SUFFIXES lib64 
	DOC "libOIS_x86_64"
)

FIND_LIBRARY(OIS_LIBRARIES_DEBUG
	PATHS ${OIS_ROOT_DIR}
	NAMES OIS_d
	PATH_SUFFIXES lib64
	DOC "libOIS_x86_64"
)

SET( OIS_LIBRARIES debug ${OIS_LIBRARIES_DEBUG} optimized ${OIS_LIBRARIES_RELEASE} ) 

FIND_PACKAGE_HANDLE_STANDARD_ARGS(OIS DEFAULT_MSG OIS_LIBRARIES OIS_INCLUDE_DIR OIS_ROOT_DIR)