IF( ${WIN32} )
	SET( WIN32_USE_PREPARED_PACKAGES_DCMTK TRUE )
ENDIF( ${WIN32} )


IF( WIN32_USE_PREPARED_PACKAGES_DCMTK )

	SET(DCMTK_Components dcmnet dcmdata ofstd )
	SET(DCMTK_LIBRARY_DIR "${CMAKE_SOURCE_DIR}/../lib/dcmtkLibs")
	
	PREPEND_STRING_TO_LIST_MEMBERS( "${DCMTK_LIBRARY_DIR}/"  DCMTK_Components DCMTK_LIBS_OPTIMIZED )
	APPEND_STRING_TO_LIST_MEMBERS( ".lib"  DCMTK_LIBS_OPTIMIZED DCMTK_LIBS_OPTIMIZED )
	INSERT_KEYWORD_BEFORE_EACH_MEMBER( "optimized" DCMTK_LIBS_OPTIMIZED DCMTK_LIBS_OPTIMIZED )
	
	PREPEND_STRING_TO_LIST_MEMBERS( "${DCMTK_LIBRARY_DIR}/"  DCMTK_Components DCMTK_LIBS_DEBUG )
	APPEND_STRING_TO_LIST_MEMBERS( "d.lib"  DCMTK_LIBS_DEBUG DCMTK_LIBS_DEBUG )
	INSERT_KEYWORD_BEFORE_EACH_MEMBER( "debug" DCMTK_LIBS_DEBUG DCMTK_LIBS_DEBUG )
		
	SET(DCMTK_LIBRARIES ${DCMTK_LIBS_DEBUG} ${DCMTK_LIBS_OPTIMIZED} netapi32 )
	SET(DCMTK_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/../include/dcmtk")

	SET( DCMTK_OPTIONS "" )
ELSE( WIN32_USE_PREPARED_PACKAGES_DCMTK )
	FIND_PACKAGE(DCMTK REQUIRED)
	SET( DCMTK_OPTIONS "HAVE_CONFIG_H" )
ENDIF( WIN32_USE_PREPARED_PACKAGES_DCMTK )

